name: Build executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Cache crates
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Upload the compiled executable
      uses: actions/upload-artifact@v3
      if: matrix.os == 'windows-latest'
      with:
        name: kant-tools.exe
        path: target/release/kant-tools.exe
    - name: Upload the compiled executable
      uses: actions/upload-artifact@v3
      if: matrix.os != 'windows-latest'
      with:
        name: kant-tools_${{ matrix.os }}
        path: target/release/kant-tools
